import { TStyleSheetItem } from './type'
export default [
    [["article","aside","details","figcaption","figure","footer","header","hgroup","main","nav","section","summary"],{"display":"block"}],
    [["audio","canvas","video"],{"display":"inline-block","*display":"inline","*zoom":"1"}],
    [["audio:not([controls])"],{"display":"none","height":"0"}],
    [["[hidden]"],{"display":"none"}],
    [["html"],{"fontSize":"100%","MsTextSizeAdjust":"100%","WebkitTextSizeAdjust":"100%"}],
    [["html","button","input","select","textarea"],{"fontFamily":"sans-serif"}],
    [["body"],{"margin":"0"}],
    [["a:focus"],{"outline":"thin dotted"}],
    [["a:active","a:hover"],{"outline":"0"}],
    [["h1"],{"fontSize":"2em","margin":"0.67em 0"}],
    [["h2"],{"fontSize":"1.5em","margin":"0.83em 0"}],
    [["h3"],{"fontSize":"1.17em","margin":"1em 0"}],
    [["h4"],{"fontSize":"1em","margin":"1.33em 0"}],
    [["h5"],{"fontSize":"0.83em","margin":"1.67em 0"}],
    [["h6"],{"fontSize":"0.67em","margin":"2.33em 0"}],
    [["abbr[title]"],{"borderBottom":"1px dotted"}],
    [["b","strong"],{"fontWeight":"bold"}],
    [["blockquote"],{"margin":"1em 40px"}],
    [["dfn"],{"fontStyle":"italic"}],
    [["hr"],{"MozBoxSizing":"content-box","boxSizing":"content-box","height":"0"}],
    [["mark"],{"background":"#ff0","color":"#000"}],
    [["p","pre"],{"margin":"1em 0"}],
    [["code","kbd","pre","samp"],{"fontFamily":"monospace, serif","_fontFamily":"'courier new', monospace","fontSize":"1em"}],
    [["pre"],{"whiteSpace":"pre-wrap","wordWrap":"break-word"}],
    [["q"],{"quotes":"none"}],
    [["q:before","q:after"],{"content":"none"}],
    [["small"],{"fontSize":"80%"}],
    [["sub","sup"],{"fontSize":"75%","lineHeight":"0","position":"relative","verticalAlign":"baseline"}],
    [["sup"],{"top":"-0.5em"}],
    [["sub"],{"bottom":"-0.25em"}],
    [["dl","menu","ol","ul"],{"margin":"1em 0"}],
    [["dd"],{"margin":"0 0 0 40px"}],
    [["menu","ol","ul"],{"padding":"0 0 0 40px"}],
    [["nav ul","nav ol"],{"listStyle":"none","listStyleImage":"none"}],
    [["img"],{"border":"0","MsInterpolationMode":"bicubic"}],
    [["svg:not(:root)"],{"overflow":"hidden"}],
    [["figure"],{"margin":"0"}],
    [["form"],{"margin":"0"}],
    [["fieldset"],{"border":"1px solid #c0c0c0","margin":"0 2px","padding":"0.35em 0.625em 0.75em"}],
    [["legend"],{"border":"0","padding":"0","whiteSpace":"normal","*marginLeft":"-7px"}],
    [["button","input","select","textarea"],{"fontSize":"100%","margin":"0","verticalAlign":"baseline","*verticalAlign":"middle"}],
    [["button","input"],{"lineHeight":"normal"}],
    [["button","select"],{"textTransform":"none"}],
    [["button","html input[type=\"button\"]","input[type=\"reset\"]","input[type=\"submit\"]"],{"WebkitAppearance":"button","cursor":"pointer","*overflow":"visible"}],
    [["button[disabled]","html input[disabled]"],{"cursor":"default"}],
    [["input[type=\"checkbox\"]","input[type=\"radio\"]"],{"boxSizing":"border-box","padding":"0","*height":"13px","*width":"13px"}],
    [["input[type=\"search\"]"],{"WebkitAppearance":"textfield","MozBoxSizing":"content-box","WebkitBoxSizing":"content-box","boxSizing":"content-box"}],
    [["input[type=\"search\"]::-webkit-search-cancel-button","input[type=\"search\"]::-webkit-search-decoration"],{"WebkitAppearance":"none"}],
    [["button::-moz-focus-inner","input::-moz-focus-inner"],{"border":"0","padding":"0"}],
    [["textarea"],{"overflow":"auto","verticalAlign":"top"}],
    [["table"],{"borderCollapse":"collapse","borderSpacing":"0"}],
    [["html"],{"lineHeight":"1.15","WebkitTextSizeAdjust":"100%"}],
    [["body"],{"margin":"0"}],
    [["main"],{"display":"block"}],
    [["h1"],{"fontSize":"2em","margin":"0.67em 0"}],
    [["hr"],{"boxSizing":"content-box","height":"0","overflow":"visible"}],
    [["pre"],{"fontFamily":"monospace, monospace","fontSize":"1em"}],
    [["a"],{"backgroundColor":"transparent"}],
    [["abbr[title]"],{"borderBottom":"none","textDecoration":"underline dotted"}],
    [["b","strong"],{"fontWeight":"bolder"}],
    [["code","kbd","samp"],{"fontFamily":"monospace, monospace","fontSize":"1em"}],
    [["small"],{"fontSize":"80%"}],
    [["sub","sup"],{"fontSize":"75%","lineHeight":"0","position":"relative","verticalAlign":"baseline"}],
    [["sub"],{"bottom":"-0.25em"}],
    [["sup"],{"top":"-0.5em"}],
    [["img"],{"borderStyle":"none"}],
    [["button","input","optgroup","select","textarea"],{"fontFamily":"inherit","fontSize":"100%","lineHeight":"1.15","margin":"0"}],
    [["button","input"],{"overflow":"visible"}],
    [["button","select"],{"textTransform":"none"}],
    [["button","[type=\"button\"]","[type=\"reset\"]","[type=\"submit\"]"],{"WebkitAppearance":"button"}],
    [["button::-moz-focus-inner","[type=\"button\"]::-moz-focus-inner","[type=\"reset\"]::-moz-focus-inner","[type=\"submit\"]::-moz-focus-inner"],{"borderStyle":"none","padding":"0"}],
    [["button:-moz-focusring","[type=\"button\"]:-moz-focusring","[type=\"reset\"]:-moz-focusring","[type=\"submit\"]:-moz-focusring"],{"outline":"1px dotted ButtonText"}],
    [["fieldset"],{"padding":"0.35em 0.75em 0.625em"}],
    [["legend"],{"boxSizing":"border-box","color":"inherit","display":"table","maxWidth":"100%","padding":"0","whiteSpace":"normal"}],
    [["progress"],{"verticalAlign":"baseline"}],
    [["textarea"],{"overflow":"auto"}],
    [["[type=\"checkbox\"]","[type=\"radio\"]"],{"boxSizing":"border-box","padding":"0"}],
    [["[type=\"number\"]::-webkit-inner-spin-button","[type=\"number\"]::-webkit-outer-spin-button"],{"height":"auto"}],
    [["[type=\"search\"]"],{"WebkitAppearance":"textfield","outlineOffset":"-2px"}],
    [["[type=\"search\"]::-webkit-search-decoration"],{"WebkitAppearance":"none"}],
    [["::-webkit-file-upload-button"],{"WebkitAppearance":"button","font":"inherit"}],
    [["details"],{"display":"block"}],
    [["summary"],{"display":"list-item"}],
    [["template"],{"display":"none"}],
    [["[hidden]"],{"display":"none"}],
    [["em"],{"fontStyle":"italic"}]
] as TStyleSheetItem[]